[auto-dark-mode-nvim]
fetch.github = "f-person/auto-dark-mode.nvim"
src.git = "https://github.com/f-person/auto-dark-mode.nvim"

[milspec-nvim]
fetch.github = "nekowinston/milspec.nvim"
src.git = "https://github.com/nekowinston/milspec.nvim"

[venv-selector-nvim]
fetch.github = "linux-cultist/venv-selector.nvim"
src.git = "https://github.com/linux-cultist/venv-selector.nvim"
src.branch = "regexp"

[vim-applescript]
fetch.github = "mityu/vim-applescript"
src.git = "https://github.com/mityu/vim-applescript"

[vim-tera]
fetch.github = "vkhitrin/vim-tera"
src.git = "https://github.com/vkhitrin/vim-tera"
