# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha-nvim = {
    pname = "alpha-nvim";
    version = "b6f4129302db197a7249e67a90de3f2b676de13e";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "b6f4129302db197a7249e67a90de3f2b676de13e";
      fetchSubmodules = false;
      sha256 = "sha256-gvPEmjM36Z7Q8K83/0ZVLN6J/2mDfEZJ7cW1u+FWf/8=";
    };
    date = "2024-08-19";
  };
  auto-dark-mode-nvim = {
    pname = "auto-dark-mode-nvim";
    version = "14cad96b80a07e9e92a0dcbe235092ed14113fb2";
    src = fetchFromGitHub {
      owner = "f-person";
      repo = "auto-dark-mode.nvim";
      rev = "14cad96b80a07e9e92a0dcbe235092ed14113fb2";
      fetchSubmodules = false;
      sha256 = "sha256-bSkS2IDkRMQCjaePFYtq39Bokgd1Bwoxgu2ceP7Bh5s=";
    };
    date = "2024-07-29";
  };
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "0b2fd861eee7595015b6561dade52fb060be10c4";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "0b2fd861eee7595015b6561dade52fb060be10c4";
      fetchSubmodules = false;
      sha256 = "sha256-VjusgJ3nEc+P/3bRjdS93qAErn6PZh7YkAAjxFF6Dxk=";
    };
    date = "2024-07-18";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-git = {
    pname = "cmp-git";
    version = "50d526dff0f6bc441b51fc269d9fdc99a50c76af";
    src = fetchFromGitHub {
      owner = "petertriho";
      repo = "cmp-git";
      rev = "50d526dff0f6bc441b51fc269d9fdc99a50c76af";
      fetchSubmodules = false;
      sha256 = "sha256-Jxda6X9KjanI+l3WaJZyohQfPrRpR9SwPn+BrIyalSA=";
    };
    date = "2024-08-20";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp_luasnip = {
    pname = "cmp_luasnip";
    version = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      fetchSubmodules = false;
      sha256 = "sha256-nUJJl2zyK/oSwz5RzI9j3gf9zpDfCImCYbPbVsyXgz8=";
    };
    date = "2023-10-09";
  };
  color-picker-nvim = {
    pname = "color-picker-nvim";
    version = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
    src = fetchFromGitHub {
      owner = "ziontee113";
      repo = "color-picker.nvim";
      rev = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
      fetchSubmodules = false;
      sha256 = "sha256-a1hpKKvBG8ey/+gbfFEK8CPawEK9EdcQbnIfi7X0C9I=";
    };
    date = "2023-05-21";
  };
  comment-nvim = {
    pname = "comment-nvim";
    version = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
    src = fetchFromGitHub {
      owner = "numtostr";
      repo = "comment.nvim";
      rev = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
      fetchSubmodules = false;
      sha256 = "sha256-h0kPue5Eqd5aeu4VoLH45pF0DmWWo1d8SnLICSQ63zc=";
    };
    date = "2024-06-09";
  };
  conform-nvim = {
    pname = "conform-nvim";
    version = "0ebe875d9c306f5fc829db38492ffff2a70d8e9d";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "0ebe875d9c306f5fc829db38492ffff2a70d8e9d";
      fetchSubmodules = false;
      sha256 = "sha256-2Axf/8l4LkjrsD1cRQ36rK6pJF5rz2Wb7tAdWSH0/4w=";
    };
    date = "2024-08-30";
  };
  copilot-cmp = {
    pname = "copilot-cmp";
    version = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot-cmp";
      rev = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
      fetchSubmodules = false;
      sha256 = "sha256-8w9go2SBkI+BrXNadWM8ZxDDfrAnZZJx6RbVHAK4+Pg=";
    };
    date = "2024-06-16";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "86537b286f18783f8b67bccd78a4ef4345679625";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "86537b286f18783f8b67bccd78a4ef4345679625";
      fetchSubmodules = false;
      sha256 = "sha256-HC1QZlqEg+RBz/8kjLadafc06UoMAjhh0UO/BWQGMY8=";
    };
    date = "2024-06-14";
  };
  crates-nvim = {
    pname = "crates-nvim";
    version = "b3b9ac6ed9618955b24bf9adede7530ef608495b";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "b3b9ac6ed9618955b24bf9adede7530ef608495b";
      fetchSubmodules = false;
      sha256 = "sha256-DcyQtuLUEuv3rQQylopSirwC/TYx8AWuR5arVJG3Eyc=";
    };
    date = "2024-09-02";
  };
  diffview-nvim = {
    pname = "diffview-nvim";
    version = "4516612fe98ff56ae0415a259ff6361a89419b0a";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "4516612fe98ff56ae0415a259ff6361a89419b0a";
      fetchSubmodules = false;
      sha256 = "sha256-SX+ybIzL/w6uyCy4iZKnWnzTFwqB1oXSgyYVAdpdKi8=";
    };
    date = "2024-06-13";
  };
  direnv-vim = {
    pname = "direnv-vim";
    version = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
    src = fetchFromGitHub {
      owner = "direnv";
      repo = "direnv.vim";
      rev = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
      fetchSubmodules = false;
      sha256 = "sha256-Lwwm95UEkS8Q0Qsoh10o3sFn48wf7v7eCX/FJJV1HMI=";
    };
    date = "2023-12-02";
  };
  dressing-nvim = {
    pname = "dressing-nvim";
    version = "c5775a888adbc50652cb370073fcfec963eca93e";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "c5775a888adbc50652cb370073fcfec963eca93e";
      fetchSubmodules = false;
      sha256 = "sha256-6T2p0hI7/WqaDFQodaDq7uiyuplVqeekayQ2equ/mC0=";
    };
    date = "2024-08-16";
  };
  fidget-nvim = {
    pname = "fidget-nvim";
    version = "d855eed8a06531a7e8fd0684889b2943f373c469";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "d855eed8a06531a7e8fd0684889b2943f373c469";
      fetchSubmodules = false;
      sha256 = "sha256-fjxdRN08BMU7jTWdhdzh8kW18ZURS9SJCwnTxuz6aFE=";
    };
    date = "2024-07-13";
  };
  flash-nvim = {
    pname = "flash-nvim";
    version = "34c7be146a91fec3555c33fe89c7d643f6ef5cf1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "34c7be146a91fec3555c33fe89c7d643f6ef5cf1";
      fetchSubmodules = false;
      sha256 = "sha256-dM3hk/wutaRHMlGiKVQoXmgj7ycV/TCorfhdSNv4OBI=";
    };
    date = "2024-07-22";
  };
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "00ebcaa159e817150bd83bfe2d51fa3b3377d5c4";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "00ebcaa159e817150bd83bfe2d51fa3b3377d5c4";
      fetchSubmodules = false;
      sha256 = "sha256-kwGyfXZ+jZ3PIniESUGBltBm2fRXV5ArNhSo+zosdco=";
    };
    date = "2024-07-14";
  };
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "1ef74b546732f185d0f806860fa5404df7614f28";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "1ef74b546732f185d0f806860fa5404df7614f28";
      fetchSubmodules = false;
      sha256 = "sha256-s3y8ZuLV00GIhizcK/zqsJOTKecql7Xn3LGYmH7NLsQ=";
    };
    date = "2024-09-04";
  };
  haskell-tools-nvim = {
    pname = "haskell-tools-nvim";
    version = "48de39f139454d1293f9081a724d07bbc83eeb49";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "haskell-tools.nvim";
      rev = "48de39f139454d1293f9081a724d07bbc83eeb49";
      fetchSubmodules = false;
      sha256 = "sha256-/LtV8AUtTBoxOgTN/eLsL1jAmgFAdeQnwaMo1ONhE1k=";
    };
    date = "2024-09-08";
  };
  indent-blankline-nvim = {
    pname = "indent-blankline-nvim";
    version = "18603eb949eba08300799f64027af11ef922283f";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "18603eb949eba08300799f64027af11ef922283f";
      fetchSubmodules = false;
      sha256 = "sha256-5+RulvASXwO2y8owz+6NbPK925llpkACSjC5TuAnUUk=";
    };
    date = "2024-09-03";
  };
  lazy-nvim = {
    pname = "lazy-nvim";
    version = "48b52b5cfcf8f88ed0aff8fde573a5cc20b1306d";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "48b52b5cfcf8f88ed0aff8fde573a5cc20b1306d";
      fetchSubmodules = false;
      sha256 = "sha256-qERgCq8exkdVQok72TAU1+xvTiy2wxcjsVwoHE59kOc=";
    };
    date = "2024-08-31";
  };
  lazydev-nvim = {
    pname = "lazydev-nvim";
    version = "491452cf1ca6f029e90ad0d0368848fac717c6d2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "491452cf1ca6f029e90ad0d0368848fac717c6d2";
      fetchSubmodules = false;
      sha256 = "sha256-D5gP2rVPYoWc8hslTrH7Z90cE7XEu+tfkD6FZzY/iPk=";
    };
    date = "2024-07-25";
  };
  lspkind-nvim = {
    pname = "lspkind-nvim";
    version = "cff4ae321a91ee3473a92ea1a8c637e3a9510aec";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "cff4ae321a91ee3473a92ea1a8c637e3a9510aec";
      fetchSubmodules = false;
      sha256 = "sha256-1KK6JhQUtA5mxwRSKU5e3pTQzZwaoAjzycBLx5X/xlA=";
    };
    date = "2024-07-25";
  };
  ltex-extra-nvim = {
    pname = "ltex-extra-nvim";
    version = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
      fetchSubmodules = false;
      sha256 = "sha256-OGeeEIF+z03DdJO2d2kzQ0lZnIYLabp6irYPqYgbCbc=";
    };
    date = "2024-06-15";
  };
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
      fetchSubmodules = false;
      sha256 = "sha256-gCm7m96PkZyrgjmt7Efc+NMZKStAq1zr7JRCYOgGDuE=";
    };
    date = "2024-08-12";
  };
  luasnip = {
    pname = "luasnip";
    version = "45db5addf8d0a201e1cf247cae4cdce605ad3768";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "45db5addf8d0a201e1cf247cae4cdce605ad3768";
      fetchSubmodules = false;
      sha256 = "sha256-1b9hT6+wUoH31JUjWHaBOJMg2juMxoA1vPfme3zBEYg=";
    };
    date = "2024-08-28";
  };
  milspec-nvim = {
    pname = "milspec-nvim";
    version = "3988464c4514e441b4f81599507bdf2815b2f9e2";
    src = fetchFromGitHub {
      owner = "nekowinston";
      repo = "milspec.nvim";
      rev = "3988464c4514e441b4f81599507bdf2815b2f9e2";
      fetchSubmodules = false;
      sha256 = "sha256-2U8yqLqTnal0CAZOD8bWrv/bprl7Tusg1H5gnasbfVY=";
    };
    date = "2024-06-08";
  };
  neoconf-nvim = {
    pname = "neoconf-nvim";
    version = "8ee287dccee562857b0abe9fe3acd6ad147f8a70";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neoconf.nvim";
      rev = "8ee287dccee562857b0abe9fe3acd6ad147f8a70";
      fetchSubmodules = false;
      sha256 = "sha256-LHLg4S5BfPYjdwkzb3yxf22Ra+IvMl2jK1FMw/HggnI=";
    };
    date = "2024-09-07";
  };
  neogen = {
    pname = "neogen";
    version = "e932ba918b56723436b77aa3efb844a11b2851ab";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "e932ba918b56723436b77aa3efb844a11b2851ab";
      fetchSubmodules = false;
      sha256 = "sha256-0/XTVOzcWuFwz/UgEhGJwmSYloBgU8DVl2cauR0Qitc=";
    };
    date = "2024-08-22";
  };
  neogit = {
    pname = "neogit";
    version = "9bc4ee89bb42be31a2f0b1da41e36e3e6cab9bbb";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "9bc4ee89bb42be31a2f0b1da41e36e3e6cab9bbb";
      fetchSubmodules = false;
      sha256 = "sha256-su9hdAVyhIhFpr2w/cXxCxW4T/VSuxHDN0XIzy06cCc=";
    };
    date = "2024-09-02";
  };
  neorepl-nvim = {
    pname = "neorepl-nvim";
    version = "15f4c4e523e1fbec74766e1967e1c2491df013c9";
    src = fetchFromGitHub {
      owner = "ii14";
      repo = "neorepl.nvim";
      rev = "15f4c4e523e1fbec74766e1967e1c2491df013c9";
      fetchSubmodules = false;
      sha256 = "sha256-PBEZDbwH1ZYAh9y2XXavbKo1SzlzO66J4e03gOh+Pwc=";
    };
    date = "2024-06-02";
  };
  neotest = {
    pname = "neotest";
    version = "6d6ad113f56edc7c3f2a77a0836ea8c1b955ebea";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest";
      rev = "6d6ad113f56edc7c3f2a77a0836ea8c1b955ebea";
      fetchSubmodules = false;
      sha256 = "sha256-ua/fV1zClX97P4aZNPzRuO382D8hm8xe4UaBxa88Hu0=";
    };
    date = "2024-08-26";
  };
  neotest-deno = {
    pname = "neotest-deno";
    version = "7136b9342aeecb675c7c16a0bde327d7fcb00a1c";
    src = fetchFromGitHub {
      owner = "MarkEmmons";
      repo = "neotest-deno";
      rev = "7136b9342aeecb675c7c16a0bde327d7fcb00a1c";
      fetchSubmodules = false;
      sha256 = "sha256-jEksgs7BDNsi8pKeZ6wEDA+pytT9oSKWbs4d0s30PuM=";
    };
    date = "2022-12-09";
  };
  neotest-go = {
    pname = "neotest-go";
    version = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest-go";
      rev = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6";
      fetchSubmodules = false;
      sha256 = "sha256-BEq6hX7TbGQV899kgzrFnSNrPUUXiPudyFrKb8COvXI=";
    };
    date = "2024-05-19";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
      fetchSubmodules = false;
      sha256 = "sha256-HnNbB5Nx65Zb5oTjED0et+bAAEVX5+8pZxwTZvxRtQ8=";
    };
    date = "2024-08-02";
  };
  noice-nvim = {
    pname = "noice-nvim";
    version = "448bb9c524a7601035449210838e374a30153172";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "448bb9c524a7601035449210838e374a30153172";
      fetchSubmodules = false;
      sha256 = "sha256-86oWl3XGuuVhaWVe6egjc7Mt8Pp7qpTMJ2EZiNlztt8=";
    };
    date = "2024-07-25";
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "61574ce6e60c815b0a0c4b5655b8486ba58089a1";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "61574ce6e60c815b0a0c4b5655b8486ba58089a1";
      fetchSubmodules = false;
      sha256 = "sha256-o2iNktcWxL0oCtCkbARMiWnTlZA8QWQHy2qeOanBlO4=";
    };
    date = "2024-06-26";
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "fd2badc24e675f947162a16c124d395bde80dbd6";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "fd2badc24e675f947162a16c124d395bde80dbd6";
      fetchSubmodules = false;
      sha256 = "sha256-iDDI5M9gyF06XhPbVj+aiFbKRMO/82/qIoLv3DKIXxo=";
    };
    date = "2024-09-02";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
      fetchSubmodules = false;
      sha256 = "sha256-NcodgUp8obTsjgc+5j2dKr0f3FelYikQTJngfZXRZzo=";
    };
    date = "2024-08-01";
  };
  nvim-colorizer-lua = {
    pname = "nvim-colorizer-lua";
    version = "194ec600488f7c7229668d0e80bd197f3a2b84ff";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "194ec600488f7c7229668d0e80bd197f3a2b84ff";
      fetchSubmodules = false;
      sha256 = "sha256-Qw7IcfM3N+7ml98ExMPBszDz9FwJPtmrVqrVDa0TJKQ=";
    };
    date = "2024-07-25";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "20a4859ebde1c9bc8e96f8cc11a20667e7fdd516";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "20a4859ebde1c9bc8e96f8cc11a20667e7fdd516";
      fetchSubmodules = false;
      sha256 = "sha256-p4MOLjxUff9PRDBLyI5JUely2uguhxiPJ6MfGU4tONY=";
    };
    date = "2024-09-05";
  };
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "db72bf6ab9f75fe841e8e11e772ee7fef6f484f1";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "db72bf6ab9f75fe841e8e11e772ee7fef6f484f1";
      fetchSubmodules = false;
      sha256 = "sha256-t5qz+EFUIKUTPH1aiiBmGJ1E+NZ18nvjNLNxQsPRS9Q=";
    };
    date = "2024-09-08";
  };
  nvim-dap-ui = {
    pname = "nvim-dap-ui";
    version = "1c351e4e417d4691da12948b6ecf966936a56d28";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "1c351e4e417d4691da12948b6ecf966936a56d28";
      fetchSubmodules = false;
      sha256 = "sha256-2ysLTiX2664QhFtEmpqM/sdao1+MLSTukxmaRTQv6UE=";
    };
    date = "2024-08-26";
  };
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "9578276dfdc5420624699744377ddd74be2d9a19";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "9578276dfdc5420624699744377ddd74be2d9a19";
      fetchSubmodules = false;
      sha256 = "sha256-MZJ+60Ia59zkKwfSio30QHhfrJXgXhFUJirzbEicd6Q=";
    };
    date = "2024-09-08";
  };
  nvim-jdtls = {
    pname = "nvim-jdtls";
    version = "99e4b2081de1d9162666cc7b563cbeb01c26b66b";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-jdtls";
      rev = "99e4b2081de1d9162666cc7b563cbeb01c26b66b";
      fetchSubmodules = false;
      sha256 = "sha256-c/8s3lBHd2NRTq0HKWx05D/8pci8GYESnLzaXBw74z8=";
    };
    date = "2024-08-05";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "bdbc65aadc708ce528efb22bca5f82a7cca6b54d";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "bdbc65aadc708ce528efb22bca5f82a7cca6b54d";
      fetchSubmodules = false;
      sha256 = "sha256-xel86Ebobiv7dgudH3+BfSOoE7XLnvMne8Jj5cItAp4=";
    };
    date = "2024-09-05";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "a428f309119086dc78dd4b19306d2d67be884eee";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "a428f309119086dc78dd4b19306d2d67be884eee";
      fetchSubmodules = false;
      sha256 = "sha256-i6imNTb1xrfBlaeOyxyIwAZ/+o6ew9C4/z34a7/BgFg=";
    };
    date = "2024-07-11";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "d333b6f167900f6d9d42a59005d82919830626bf";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "d333b6f167900f6d9d42a59005d82919830626bf";
      fetchSubmodules = false;
      sha256 = "sha256-wxyHwL/uFdp6w32CVHgSOWkzRrIRuFvWh+J2401RAAA=";
    };
    date = "2024-05-17";
  };
  nvim-spectre = {
    pname = "nvim-spectre";
    version = "ba7fb777edff6c1fbbeffd343e113af64c04e90a";
    src = fetchFromGitHub {
      owner = "nvim-pack";
      repo = "nvim-spectre";
      rev = "ba7fb777edff6c1fbbeffd343e113af64c04e90a";
      fetchSubmodules = false;
      sha256 = "sha256-FnpNvl6bxE6vW0Bwg+IeS0/rEDPpDNOSMQgib2Wzkwg=";
    };
    cargoLock."spectre_oxi/Cargo.lock" = {
      lockFile = ./nvim-spectre-ba7fb777edff6c1fbbeffd343e113af64c04e90a/spectre_oxi/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-07-30";
  };
  nvim-surround = {
    pname = "nvim-surround";
    version = "ec2dc7671067e0086cdf29c2f5df2dd909d5f71f";
    src = fetchFromGitHub {
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "ec2dc7671067e0086cdf29c2f5df2dd909d5f71f";
      fetchSubmodules = false;
      sha256 = "sha256-DCNfT//qMnzIu4V9or3Q39h4XzLz9P4twtHnQHV2rrQ=";
    };
    date = "2024-06-24";
  };
  nvim-tree-lua = {
    pname = "nvim-tree-lua";
    version = "cb57691536702ea479afd294657f6a589d0faae1";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "cb57691536702ea479afd294657f6a589d0faae1";
      fetchSubmodules = false;
      sha256 = "sha256-YCMbsl5YQzSlbimzMp0fnSNwka3etz3sVec/yTpxJzA=";
    };
    date = "2024-09-08";
  };
  nvim-treesitter-context = {
    pname = "nvim-treesitter-context";
    version = "e6cc783b74606d97ca9eff6494e3f5c2ca603a50";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "e6cc783b74606d97ca9eff6494e3f5c2ca603a50";
      fetchSubmodules = false;
      sha256 = "sha256-wDRd6qFbfHYwWNCfc7Ixg/aUkGUVRTt/TEBvrTn+IEg=";
    };
    date = "2024-09-02";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "bf8d2ad35d1d1a687eae6c065c3d524f7ab61b23";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "bf8d2ad35d1d1a687eae6c065c3d524f7ab61b23";
      fetchSubmodules = false;
      sha256 = "sha256-qDk74rGr9uO/WdSoMZMr8i4bxjlkGDRwpJKaQA+MdgE=";
    };
    date = "2024-09-08";
  };
  nvim-ts-autotag = {
    pname = "nvim-ts-autotag";
    version = "e239a560f338be31337e7abc3ee42515daf23f5e";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "e239a560f338be31337e7abc3ee42515daf23f5e";
      fetchSubmodules = false;
      sha256 = "sha256-QEzUKvT+ChYSa9F4zg3Lw+7Sj0JzJem9nh2mWmS8Y+I=";
    };
    date = "2024-08-27";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "9793801f974bba70e4ac5d7eae6c4f5659993d8e";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "9793801f974bba70e4ac5d7eae6c4f5659993d8e";
      fetchSubmodules = false;
      sha256 = "sha256-2X72Xv+S9mZ79x1k28LxKH7RnARwB3ZHGGSzIkeuWj8=";
    };
    date = "2024-09-06";
  };
  octo-nvim = {
    pname = "octo-nvim";
    version = "fd50872494abd1cb580c604f1f52aae2257f7220";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "fd50872494abd1cb580c604f1f52aae2257f7220";
      fetchSubmodules = false;
      sha256 = "sha256-jXPIz+L4XuXk62US29m0c6giswNccMfUiQrY0YhoVKM=";
    };
    date = "2024-09-06";
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "ec289423a1693aeae6cd0d503bac2856af74edaa";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "ec289423a1693aeae6cd0d503bac2856af74edaa";
      fetchSubmodules = false;
      sha256 = "sha256-6Gm+4zZ80quI5iAW6qPAWTq9h1csPWkZFZ9KnFgYRM0=";
    };
    date = "2024-08-19";
  };
  presence-nvim = {
    pname = "presence-nvim";
    version = "87c857a56b7703f976d3a5ef15967d80508df6e6";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "87c857a56b7703f976d3a5ef15967d80508df6e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZpsunLsn//zYgUtmAm5FqKVueVd/Pa1r55ZDqxCimBk=";
    };
    date = "2023-01-29";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "5f73b24aeb94f5274c218955573153c69ce4d1ee";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "5f73b24aeb94f5274c218955573153c69ce4d1ee";
      fetchSubmodules = false;
      sha256 = "sha256-P5AXMUYetOgpPZKO/xF1nJnpIE7tRKWEvfdOLaDBlGM=";
    };
    date = "2024-09-03";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "c968ee2efb763f63e45941bb20279a1a2b85d6ff";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "c968ee2efb763f63e45941bb20279a1a2b85d6ff";
      fetchSubmodules = false;
      sha256 = "sha256-38Ju0eUvXuUHbeOqijcuwhq2HU1wJnkVUxP23YoloJU=";
    };
    date = "2024-09-08";
  };
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "28a6a50e5b7b963dc6a5d2defc40e158231a67ed";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "28a6a50e5b7b963dc6a5d2defc40e158231a67ed";
      fetchSubmodules = false;
      sha256 = "sha256-hixM06QouTz3XAG8NbUuLSBe1azZObcaSYiweBY0/nE=";
    };
    date = "2024-09-06";
  };
  tagalong-vim = {
    pname = "tagalong-vim";
    version = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
    src = fetchFromGitHub {
      owner = "AndrewRadev";
      repo = "tagalong.vim";
      rev = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
      fetchSubmodules = false;
      sha256 = "sha256-zTdq7hg+tPTy803o+f3gIzb7TCw4KRgKAaLf7bBC1A4=";
    };
    date = "2023-09-07";
  };
  telescope-file-browser-nvim = {
    pname = "telescope-file-browser-nvim";
    version = "c5a14e0550699a7db575805cdb9ddc969ba0f1f5";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "c5a14e0550699a7db575805cdb9ddc969ba0f1f5";
      fetchSubmodules = false;
      sha256 = "sha256-Ij+rSXvbIc/6YMbfjN6VDCfu6jXV0K5mf+NzNSVgB50=";
    };
    date = "2024-09-05";
  };
  telescope-nvim = {
    pname = "telescope-nvim";
    version = "5972437de807c3bc101565175da66a1aa4f8707a";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "5972437de807c3bc101565175da66a1aa4f8707a";
      fetchSubmodules = false;
      sha256 = "sha256-rNzfnORvbKoglt20i/rKmlkysPUBlB89F6dRKgB5MKU=";
    };
    date = "2024-08-15";
  };
  telescope-project-nvim = {
    pname = "telescope-project-nvim";
    version = "1aaf16580a614601a7f7077d9639aeb457dc5559";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "1aaf16580a614601a7f7077d9639aeb457dc5559";
      fetchSubmodules = false;
      sha256 = "sha256-touMCltcnqkrQYV1NtNeWLQeFVGt+WM3aIWIdKilA7w=";
    };
    date = "2023-12-01";
  };
  todo-comments-nvim = {
    pname = "todo-comments-nvim";
    version = "319c01b99b7a8c9ac2066bf0efd4d6ec68fef444";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "319c01b99b7a8c9ac2066bf0efd4d6ec68fef444";
      fetchSubmodules = false;
      sha256 = "sha256-gZzd+M9WcrBPucSFd/6MOmGqWm9X89+zPGKmF7ggW1k=";
    };
    date = "2024-08-31";
  };
  toggleterm-nvim = {
    pname = "toggleterm-nvim";
    version = "137d06fb103952a0fb567882bb8527e2f92d327d";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "137d06fb103952a0fb567882bb8527e2f92d327d";
      fetchSubmodules = false;
      sha256 = "sha256-VlHE5nFHDO6GRRM44TqtcWSk2k0NfeCndp7of/35ta4=";
    };
    date = "2024-08-08";
  };
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "6efc446226679fda0547c0fd6a7892fd5f5b15d8";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "6efc446226679fda0547c0fd6a7892fd5f5b15d8";
      fetchSubmodules = false;
      sha256 = "sha256-db/riM3Kq+QgGUqRxJHA4HYXJE31276hrUrDj4UhC2g=";
    };
    date = "2024-07-22";
  };
  twilight-nvim = {
    pname = "twilight-nvim";
    version = "1584c0b0a979b71fd86b18d302ba84e9aba85b1b";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "twilight.nvim";
      rev = "1584c0b0a979b71fd86b18d302ba84e9aba85b1b";
      fetchSubmodules = false;
      sha256 = "sha256-sC9DSgkQw+jHvi+xUP+iWSSLV0kIWWmrom2Mq5q+RJo=";
    };
    date = "2024-07-22";
  };
  typescript-tools-nvim = {
    pname = "typescript-tools-nvim";
    version = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
      fetchSubmodules = false;
      sha256 = "sha256-8WH/eCff1liDVaezZFvu6RqCtXU4Uwq80BlWiH+tQME=";
    };
    date = "2024-07-18";
  };
  venv-selector-nvim = {
    pname = "venv-selector-nvim";
    version = "4cf9fdebe3daca2b4459a275a123b2536fa60388";
    src = fetchFromGitHub {
      owner = "linux-cultist";
      repo = "venv-selector.nvim";
      rev = "4cf9fdebe3daca2b4459a275a123b2536fa60388";
      fetchSubmodules = false;
      sha256 = "sha256-X1pWA6GbhKKqGJ1wjv0yk8TNre8oxEEvmaKyBWbd0cA=";
    };
    date = "2024-09-07";
  };
  vim-applescript = {
    pname = "vim-applescript";
    version = "a39af8fc7e4caf581366e2917d558f6232e4db36";
    src = fetchFromGitHub {
      owner = "mityu";
      repo = "vim-applescript";
      rev = "a39af8fc7e4caf581366e2917d558f6232e4db36";
      fetchSubmodules = false;
      sha256 = "sha256-9asF5VMaKz3lfSsCTrvkicffgMbHY88wDZ+LJR9QTvY=";
    };
    date = "2022-01-21";
  };
  vim-dadbod = {
    pname = "vim-dadbod";
    version = "7888cb7164d69783d3dce4e0283decd26b82538b";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-dadbod";
      rev = "7888cb7164d69783d3dce4e0283decd26b82538b";
      fetchSubmodules = false;
      sha256 = "sha256-8wnUSYctVn3JeCVz2fdi9qcKi8ZyA4To+xs4WaP6rog=";
    };
    date = "2024-05-31";
  };
  vim-dadbod-completion = {
    pname = "vim-dadbod-completion";
    version = "880f7e9f2959e567c718d52550f9fae1aa07aa81";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-completion";
      rev = "880f7e9f2959e567c718d52550f9fae1aa07aa81";
      fetchSubmodules = false;
      sha256 = "sha256-kci8ksgSRPmRhwTYw7Ya1v4hwPjN4BLFjV6+6YiK1hA=";
    };
    date = "2024-08-15";
  };
  vim-dadbod-ui = {
    pname = "vim-dadbod-ui";
    version = "aa003f514ba0b1250ba0f284f031d011bb9e83e8";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-ui";
      rev = "aa003f514ba0b1250ba0f284f031d011bb9e83e8";
      fetchSubmodules = false;
      sha256 = "sha256-iymhxKlQ5h/KVH9T/iXYgRgnZlscKfPgIi46BikkOgQ=";
    };
    date = "2024-09-05";
  };
  vim-gnupg = {
    pname = "vim-gnupg";
    version = "f9b608f29003dfde6450931dc0f495a912973a88";
    src = fetchFromGitHub {
      owner = "jamessan";
      repo = "vim-gnupg";
      rev = "f9b608f29003dfde6450931dc0f495a912973a88";
      fetchSubmodules = false;
      sha256 = "sha256-B6hSEeNjJdDUDjM0DlmAxc3zRRcJz91//GPk6rCWn6I=";
    };
    date = "2022-05-18";
  };
  vim-helm = {
    pname = "vim-helm";
    version = "ae1ebc160d2b9b90108477ab10df7a4fc501e358";
    src = fetchFromGitHub {
      owner = "towolf";
      repo = "vim-helm";
      rev = "ae1ebc160d2b9b90108477ab10df7a4fc501e358";
      fetchSubmodules = false;
      sha256 = "sha256-xrZ8MCuewAN/qIqSrbTuCtZocYZvXSSet26MYrYumxI=";
    };
    date = "2024-05-31";
  };
  vim-table-mode = {
    pname = "vim-table-mode";
    version = "e4365bde024f73e205eefa2fb78e3029ddb92ea9";
    src = fetchFromGitHub {
      owner = "dhruvasagar";
      repo = "vim-table-mode";
      rev = "e4365bde024f73e205eefa2fb78e3029ddb92ea9";
      fetchSubmodules = false;
      sha256 = "sha256-8p40cId8dQVhXHuusk2Mn2esRZm8vcY5EZbAXBPU/Fg=";
    };
    date = "2024-03-14";
  };
  vim-tera = {
    pname = "vim-tera";
    version = "235fb7e7e76dfffc0596fabc1e090880bce48844";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "vim-tera";
      rev = "235fb7e7e76dfffc0596fabc1e090880bce48844";
      fetchSubmodules = false;
      sha256 = "sha256-Zs3rRAwTp9iZc5oOkiR88j7LX7YmDrEELXt29h+j55w=";
    };
    date = "2024-05-29";
  };
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "bfec3d6bc0a9b0b2cb11644642f78c2c3915eef0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "bfec3d6bc0a9b0b2cb11644642f78c2c3915eef0";
      fetchSubmodules = false;
      sha256 = "sha256-FY0KM0F2keMCqB5QhwfGS4w2wQOOeCXgZEa3U7Q1Bek=";
    };
    date = "2024-08-31";
  };
  winshift-nvim = {
    pname = "winshift-nvim";
    version = "37468ed6f385dfb50402368669766504c0e15583";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "winshift.nvim";
      rev = "37468ed6f385dfb50402368669766504c0e15583";
      fetchSubmodules = false;
      sha256 = "sha256-mW3kaducHWRlDx18WcwcbWDlNnAyHgELS3XjpeFFCgs=";
    };
    date = "2022-09-06";
  };
  zen-mode-nvim = {
    pname = "zen-mode-nvim";
    version = "29b292bdc58b76a6c8f294c961a8bf92c5a6ebd6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "29b292bdc58b76a6c8f294c961a8bf92c5a6ebd6";
      fetchSubmodules = false;
      sha256 = "sha256-iHGsnFG1PBup3/+JbSwXf/TerQ7PNXkp9gKVznmRbTE=";
    };
    date = "2024-07-22";
  };
}
