# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha-nvim = {
    pname = "alpha-nvim";
    version = "bf3c8bb8c02ed3d9644cc5bbc48e2bdc39349cd7";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "bf3c8bb8c02ed3d9644cc5bbc48e2bdc39349cd7";
      fetchSubmodules = false;
      sha256 = "sha256-33lhPP1C4TGo0UQJ61bwRHaiOMAB7XNehcZGaFXOPjQ=";
    };
    date = "2024-09-30";
  };
  auto-dark-mode-nvim = {
    pname = "auto-dark-mode-nvim";
    version = "d365beccca05ffcb01e50109f2adca2459c3995a";
    src = fetchFromGitHub {
      owner = "f-person";
      repo = "auto-dark-mode.nvim";
      rev = "d365beccca05ffcb01e50109f2adca2459c3995a";
      fetchSubmodules = false;
      sha256 = "sha256-pZpFZ5GwVxz74CUDA9v970lcH3NNo5Rvg+9L3/87QV8=";
    };
    date = "2024-10-09";
  };
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "5cc447cb2b463cb499c82eaeabbed4f5fa6a0a44";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "5cc447cb2b463cb499c82eaeabbed4f5fa6a0a44";
      fetchSubmodules = false;
      sha256 = "sha256-MpSX8a51Avc9O1XxfWIDOVLiqD7omwAFIwSa02oXNs0=";
    };
    date = "2024-10-24";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-git = {
    pname = "cmp-git";
    version = "ec049036e354ed8ed0215f2427112882e1ea7051";
    src = fetchFromGitHub {
      owner = "petertriho";
      repo = "cmp-git";
      rev = "ec049036e354ed8ed0215f2427112882e1ea7051";
      fetchSubmodules = false;
      sha256 = "sha256-42DcNg7S8Ov9qgvuHaIz3X+axAKHOgD40ys+8ixewEU=";
    };
    date = "2024-10-27";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp_luasnip = {
    pname = "cmp_luasnip";
    version = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      fetchSubmodules = false;
      sha256 = "sha256-nUJJl2zyK/oSwz5RzI9j3gf9zpDfCImCYbPbVsyXgz8=";
    };
    date = "2023-10-09";
  };
  color-picker-nvim = {
    pname = "color-picker-nvim";
    version = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
    src = fetchFromGitHub {
      owner = "ziontee113";
      repo = "color-picker.nvim";
      rev = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
      fetchSubmodules = false;
      sha256 = "sha256-a1hpKKvBG8ey/+gbfFEK8CPawEK9EdcQbnIfi7X0C9I=";
    };
    date = "2023-05-21";
  };
  comment-nvim = {
    pname = "comment-nvim";
    version = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
    src = fetchFromGitHub {
      owner = "numtostr";
      repo = "comment.nvim";
      rev = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
      fetchSubmodules = false;
      sha256 = "sha256-h0kPue5Eqd5aeu4VoLH45pF0DmWWo1d8SnLICSQ63zc=";
    };
    date = "2024-06-09";
  };
  conform-nvim = {
    pname = "conform-nvim";
    version = "6a28c90082a67f62a323ab90d988e000a718a8c7";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "6a28c90082a67f62a323ab90d988e000a718a8c7";
      fetchSubmodules = false;
      sha256 = "sha256-eqOesJnvWazHBt97cSU1S9q4Jmx1+C/3Z+KH1kuy1Tg=";
    };
    date = "2024-10-27";
  };
  copilot-cmp = {
    pname = "copilot-cmp";
    version = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot-cmp";
      rev = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
      fetchSubmodules = false;
      sha256 = "sha256-8w9go2SBkI+BrXNadWM8ZxDDfrAnZZJx6RbVHAK4+Pg=";
    };
    date = "2024-06-16";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "f8d8d872bb319f640d5177dad5fbf01f7a16d7d0";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "f8d8d872bb319f640d5177dad5fbf01f7a16d7d0";
      fetchSubmodules = false;
      sha256 = "sha256-UY6N2Q+egh+Cn4REZXrSGH9ElWQBedl0n8tWJvGe7vs=";
    };
    date = "2024-10-18";
  };
  crates-nvim = {
    pname = "crates-nvim";
    version = "8bf8358ee326d5d8c11dcd7ac0bcc9ff97dbc785";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "8bf8358ee326d5d8c11dcd7ac0bcc9ff97dbc785";
      fetchSubmodules = false;
      sha256 = "sha256-DIG0MXRTit4iEVoLlgsTK4znjam/QDjeZEpIDn6KHiE=";
    };
    date = "2024-09-26";
  };
  diffview-nvim = {
    pname = "diffview-nvim";
    version = "4516612fe98ff56ae0415a259ff6361a89419b0a";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "4516612fe98ff56ae0415a259ff6361a89419b0a";
      fetchSubmodules = false;
      sha256 = "sha256-SX+ybIzL/w6uyCy4iZKnWnzTFwqB1oXSgyYVAdpdKi8=";
    };
    date = "2024-06-13";
  };
  direnv-vim = {
    pname = "direnv-vim";
    version = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
    src = fetchFromGitHub {
      owner = "direnv";
      repo = "direnv.vim";
      rev = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
      fetchSubmodules = false;
      sha256 = "sha256-Lwwm95UEkS8Q0Qsoh10o3sFn48wf7v7eCX/FJJV1HMI=";
    };
    date = "2023-12-02";
  };
  dressing-nvim = {
    pname = "dressing-nvim";
    version = "1b7921eecc65af1baf8ac1dc06f0794934cbcfb2";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "1b7921eecc65af1baf8ac1dc06f0794934cbcfb2";
      fetchSubmodules = false;
      sha256 = "sha256-EtLYhAwoSoHyGiGrHAVYL4/CqcgO4rSbV6otO3V08hM=";
    };
    date = "2024-09-17";
  };
  fidget-nvim = {
    pname = "fidget-nvim";
    version = "d855eed8a06531a7e8fd0684889b2943f373c469";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "d855eed8a06531a7e8fd0684889b2943f373c469";
      fetchSubmodules = false;
      sha256 = "sha256-fjxdRN08BMU7jTWdhdzh8kW18ZURS9SJCwnTxuz6aFE=";
    };
    date = "2024-07-13";
  };
  flash-nvim = {
    pname = "flash-nvim";
    version = "34c7be146a91fec3555c33fe89c7d643f6ef5cf1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "34c7be146a91fec3555c33fe89c7d643f6ef5cf1";
      fetchSubmodules = false;
      sha256 = "sha256-dM3hk/wutaRHMlGiKVQoXmgj7ycV/TCorfhdSNv4OBI=";
    };
    date = "2024-07-22";
  };
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
      fetchSubmodules = false;
      sha256 = "sha256-H94Ryad0ZsSg/gioUgW+7sowij7GgtEUMNFi1IOZAys=";
    };
    date = "2024-10-07";
  };
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "ee7634ab4f0a6606438fe13e16cbf2065589a5ed";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "ee7634ab4f0a6606438fe13e16cbf2065589a5ed";
      fetchSubmodules = false;
      sha256 = "sha256-jR7/rX2bsOMkWc4MHMRlBDdELgl8JOVjGOcx6bl/nYw=";
    };
    date = "2024-10-20";
  };
  haskell-tools-nvim = {
    pname = "haskell-tools-nvim";
    version = "4a7516d44e073dfbc3c3df4af06d72fbce019474";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "haskell-tools.nvim";
      rev = "4a7516d44e073dfbc3c3df4af06d72fbce019474";
      fetchSubmodules = false;
      sha256 = "sha256-3pkXcPlOL113Hm9yVUjJbuXVHw+P3gJxm65fzTIvIII=";
    };
    date = "2024-10-27";
  };
  indent-blankline-nvim = {
    pname = "indent-blankline-nvim";
    version = "e7a4442e055ec953311e77791546238d1eaae507";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "e7a4442e055ec953311e77791546238d1eaae507";
      fetchSubmodules = false;
      sha256 = "sha256-OKtaibgT9uPQQmddfj7YKgAYc7lz4ne1dbUz9PdRAvA=";
    };
    date = "2024-10-07";
  };
  lazy-nvim = {
    pname = "lazy-nvim";
    version = "cf8ecc2c5e4332760431a33534240b0cbc6680ab";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "cf8ecc2c5e4332760431a33534240b0cbc6680ab";
      fetchSubmodules = false;
      sha256 = "sha256-TIE7jK172t5eKLqMo/cNnRmXce5rp4qQMlF1lAQFnv4=";
    };
    date = "2024-10-22";
  };
  lazydev-nvim = {
    pname = "lazydev-nvim";
    version = "491452cf1ca6f029e90ad0d0368848fac717c6d2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "491452cf1ca6f029e90ad0d0368848fac717c6d2";
      fetchSubmodules = false;
      sha256 = "sha256-D5gP2rVPYoWc8hslTrH7Z90cE7XEu+tfkD6FZzY/iPk=";
    };
    date = "2024-07-25";
  };
  lspkind-nvim = {
    pname = "lspkind-nvim";
    version = "a700f1436d4a938b1a1a93c9962dc796afbaef4d";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "a700f1436d4a938b1a1a93c9962dc796afbaef4d";
      fetchSubmodules = false;
      sha256 = "sha256-/ifgjqqCQw67l3+gUs00tt860pa92M1WYdjdZ0lhxak=";
    };
    date = "2024-10-26";
  };
  ltex-extra-nvim = {
    pname = "ltex-extra-nvim";
    version = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
      fetchSubmodules = false;
      sha256 = "sha256-OGeeEIF+z03DdJO2d2kzQ0lZnIYLabp6irYPqYgbCbc=";
    };
    date = "2024-06-15";
  };
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
      fetchSubmodules = false;
      sha256 = "sha256-gCm7m96PkZyrgjmt7Efc+NMZKStAq1zr7JRCYOgGDuE=";
    };
    date = "2024-08-12";
  };
  luasnip = {
    pname = "luasnip";
    version = "787dee55ca364cc9119787165418fe93b74c1842";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "787dee55ca364cc9119787165418fe93b74c1842";
      fetchSubmodules = false;
      sha256 = "sha256-YGJrw20jZLzOwvBYptZG/vQQpHuk9WiH5guW2DqDTSw=";
    };
    date = "2024-10-23";
  };
  luvit-meta = {
    pname = "luvit-meta";
    version = "ce76f6f6cdc9201523a5875a4471dcfe0186eb60";
    src = fetchFromGitHub {
      owner = "Bilal2453";
      repo = "luvit-meta";
      rev = "ce76f6f6cdc9201523a5875a4471dcfe0186eb60";
      fetchSubmodules = false;
      sha256 = "sha256-zAAptV/oLuLAAsa2zSB/6fxlElk4+jNZd/cPr9oxFig=";
    };
    date = "2024-01-20";
  };
  milspec-nvim = {
    pname = "milspec-nvim";
    version = "3988464c4514e441b4f81599507bdf2815b2f9e2";
    src = fetchFromGitHub {
      owner = "nekowinston";
      repo = "milspec.nvim";
      rev = "3988464c4514e441b4f81599507bdf2815b2f9e2";
      fetchSubmodules = false;
      sha256 = "sha256-2U8yqLqTnal0CAZOD8bWrv/bprl7Tusg1H5gnasbfVY=";
    };
    date = "2024-06-08";
  };
  neoconf-nvim = {
    pname = "neoconf-nvim";
    version = "658710f44c13ca44b131b51938dc009511dc2063";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neoconf.nvim";
      rev = "658710f44c13ca44b131b51938dc009511dc2063";
      fetchSubmodules = false;
      sha256 = "sha256-83dqpG8t2/uulGFZiIKKsAtgPB2qByPkSCEkBXI2/Kc=";
    };
    date = "2024-10-28";
  };
  neogen = {
    pname = "neogen";
    version = "e932ba918b56723436b77aa3efb844a11b2851ab";
    src = fetchFromGitHub {
      owner = "danymat";
      repo = "neogen";
      rev = "e932ba918b56723436b77aa3efb844a11b2851ab";
      fetchSubmodules = false;
      sha256 = "sha256-0/XTVOzcWuFwz/UgEhGJwmSYloBgU8DVl2cauR0Qitc=";
    };
    date = "2024-08-22";
  };
  neogit = {
    pname = "neogit";
    version = "51450329e04860f71a31d8c7ef5178fce6e60524";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "51450329e04860f71a31d8c7ef5178fce6e60524";
      fetchSubmodules = false;
      sha256 = "sha256-yKB9cB/zk/Xzefddmd2zqdhtItV2m7IIhtYjqgCdV2g=";
    };
    date = "2024-10-26";
  };
  neorepl-nvim = {
    pname = "neorepl-nvim";
    version = "15f4c4e523e1fbec74766e1967e1c2491df013c9";
    src = fetchFromGitHub {
      owner = "ii14";
      repo = "neorepl.nvim";
      rev = "15f4c4e523e1fbec74766e1967e1c2491df013c9";
      fetchSubmodules = false;
      sha256 = "sha256-PBEZDbwH1ZYAh9y2XXavbKo1SzlzO66J4e03gOh+Pwc=";
    };
    date = "2024-06-02";
  };
  neotest = {
    pname = "neotest";
    version = "6d3d22cdad49999ef774ebe1bc250a4994038964";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest";
      rev = "6d3d22cdad49999ef774ebe1bc250a4994038964";
      fetchSubmodules = false;
      sha256 = "sha256-AD1smQZ40opN557WlpwNr/PKCQ4LEs/5wjHFsEdi6oM=";
    };
    date = "2024-10-02";
  };
  neotest-deno = {
    pname = "neotest-deno";
    version = "7136b9342aeecb675c7c16a0bde327d7fcb00a1c";
    src = fetchFromGitHub {
      owner = "MarkEmmons";
      repo = "neotest-deno";
      rev = "7136b9342aeecb675c7c16a0bde327d7fcb00a1c";
      fetchSubmodules = false;
      sha256 = "sha256-jEksgs7BDNsi8pKeZ6wEDA+pytT9oSKWbs4d0s30PuM=";
    };
    date = "2022-12-09";
  };
  neotest-go = {
    pname = "neotest-go";
    version = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "neotest-go";
      rev = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6";
      fetchSubmodules = false;
      sha256 = "sha256-BEq6hX7TbGQV899kgzrFnSNrPUUXiPudyFrKb8COvXI=";
    };
    date = "2024-05-19";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "ce43f2eb2a52492157d7742e5f684b9a42bb3e5c";
      fetchSubmodules = false;
      sha256 = "sha256-W9jtfVXHC8MQJwdbxakNqhd+xh/auQb3U09XKdN2Wzw=";
    };
    date = "2024-10-09";
  };
  noice-nvim = {
    pname = "noice-nvim";
    version = "df448c649ef6bc5a6a633a44f2ad0ed8d4442499";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "df448c649ef6bc5a6a633a44f2ad0ed8d4442499";
      fetchSubmodules = false;
      sha256 = "sha256-9ivgP145phRzu6OD2nwqjgD8glCThnDjS31XHsjbVuM=";
    };
    date = "2024-10-02";
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "b58e2bfda5cea347c9d58b7f11cf3012c7b3953f";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "b58e2bfda5cea347c9d58b7f11cf3012c7b3953f";
      fetchSubmodules = false;
      sha256 = "sha256-90Wq+vT361mTaGU/SvAezqJkX9HHmZ2GI2fKBDxPn04=";
    };
    date = "2024-09-15";
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "ee297f215e95a60b01fde33275cc3c820eddeebe";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "ee297f215e95a60b01fde33275cc3c820eddeebe";
      fetchSubmodules = false;
      sha256 = "sha256-pqYOaEjKUd5YLVWX0Bf/kYT+sBlN1D24rOBuIz2BIqk=";
    };
    date = "2024-10-01";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "29fb4854573355792df9e156cb779f0d31308796";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "29fb4854573355792df9e156cb779f0d31308796";
      fetchSubmodules = false;
      sha256 = "sha256-dAsXxv1RtgMc1i5QrR2xqOeK6aRgYNqdYyTXVBXhVJ4=";
    };
    date = "2024-10-21";
  };
  nvim-colorizer-lua = {
    pname = "nvim-colorizer-lua";
    version = "0671e0eabc6842676d3310370e8fae4e1c51d7f9";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "0671e0eabc6842676d3310370e8fae4e1c51d7f9";
      fetchSubmodules = false;
      sha256 = "sha256-Ffi1Q5+AI+Ysi2T56myGWmAzzyq6wW0J/Pwoc3B0ncY=";
    };
    date = "2024-09-11";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "7ff6936010b7222fea2caea0f67ed77f1b7c60dd";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "7ff6936010b7222fea2caea0f67ed77f1b7c60dd";
      fetchSubmodules = false;
      sha256 = "sha256-zN0GTcnUBDfSmvmZd9kBrgW/k3aqbzUlVzgf7wNih40=";
    };
    date = "2024-09-28";
  };
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "3e3dd98d4d83715c9e0e429b4a5da7bd706e6ceb";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "3e3dd98d4d83715c9e0e429b4a5da7bd706e6ceb";
      fetchSubmodules = false;
      sha256 = "sha256-Ck7OErQRcK4Udfzon8b+UgTO1PY0OF2LceJieDdXypw=";
    };
    date = "2024-10-24";
  };
  nvim-dap-ui = {
    pname = "nvim-dap-ui";
    version = "ffa89839f97bad360e78428d5c740fdad9a0ff02";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "ffa89839f97bad360e78428d5c740fdad9a0ff02";
      fetchSubmodules = false;
      sha256 = "sha256-kg7lyVBeuBqPCVzvt3pBoonQupgf1nGh3EvCF/astf4=";
    };
    date = "2024-10-02";
  };
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "52638640ae309cacdaff785fdbb854437bd1ee5c";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "52638640ae309cacdaff785fdbb854437bd1ee5c";
      fetchSubmodules = false;
      sha256 = "sha256-5v9siuGGM7WEyP0uEwnHWjrHShYBZS56bM5r1YxrCec=";
    };
    date = "2024-10-04";
  };
  nvim-jdtls = {
    pname = "nvim-jdtls";
    version = "efe813854432a314b472226dca813f0f2598d44a";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-jdtls";
      rev = "efe813854432a314b472226dca813f0f2598d44a";
      fetchSubmodules = false;
      sha256 = "sha256-r9qbunFJ62IqibVAdGbLsWSwYL53YKElLy98ArsK5V8=";
    };
    date = "2024-09-26";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "28b205ebe73a18f401e040585106f9bafd8ff21f";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "28b205ebe73a18f401e040585106f9bafd8ff21f";
      fetchSubmodules = false;
      sha256 = "sha256-DkDe2PoK8jNqITyfiUv3fcuMQTkcMNBZM2l0TEC7vhM=";
    };
    date = "2024-10-26";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-nio = {
    pname = "nvim-nio";
    version = "a428f309119086dc78dd4b19306d2d67be884eee";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "a428f309119086dc78dd4b19306d2d67be884eee";
      fetchSubmodules = false;
      sha256 = "sha256-i6imNTb1xrfBlaeOyxyIwAZ/+o6ew9C4/z34a7/BgFg=";
    };
    date = "2024-07-11";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "fbef5d32be8466dd76544a257d3f3dce20082a07";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "fbef5d32be8466dd76544a257d3f3dce20082a07";
      fetchSubmodules = false;
      sha256 = "sha256-Sd7IR5roXHOKRCxhqtYMhWfEltyRJMDEMDO/ecSKenE=";
    };
    date = "2024-09-22";
  };
  nvim-spectre = {
    pname = "nvim-spectre";
    version = "08be31c104df3b4b049607694ebb2b6ced4f928b";
    src = fetchFromGitHub {
      owner = "nvim-pack";
      repo = "nvim-spectre";
      rev = "08be31c104df3b4b049607694ebb2b6ced4f928b";
      fetchSubmodules = false;
      sha256 = "sha256-W9hCUSJfXNepdGvff1ZYAN+67/W+6NjarNAl9a5/YRM=";
    };
    cargoLock."spectre_oxi/Cargo.lock" = {
      lockFile = ./nvim-spectre-08be31c104df3b4b049607694ebb2b6ced4f928b/spectre_oxi/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-10-27";
  };
  nvim-surround = {
    pname = "nvim-surround";
    version = "ec2dc7671067e0086cdf29c2f5df2dd909d5f71f";
    src = fetchFromGitHub {
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "ec2dc7671067e0086cdf29c2f5df2dd909d5f71f";
      fetchSubmodules = false;
      sha256 = "sha256-DCNfT//qMnzIu4V9or3Q39h4XzLz9P4twtHnQHV2rrQ=";
    };
    date = "2024-06-24";
  };
  nvim-tree-lua = {
    pname = "nvim-tree-lua";
    version = "8f974879a04b93fff68b4627087782e76cdf2ed0";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "8f974879a04b93fff68b4627087782e76cdf2ed0";
      fetchSubmodules = false;
      sha256 = "sha256-ZKMDiYUdATcI98WQSWbJlkyBMx4/e8w8SPjUISyVeEM=";
    };
    date = "2024-10-28";
  };
  nvim-treesitter-context = {
    pname = "nvim-treesitter-context";
    version = "5bd21aa75aa9e24c0680b23fc88380cd80a53641";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "5bd21aa75aa9e24c0680b23fc88380cd80a53641";
      fetchSubmodules = false;
      sha256 = "sha256-9ECTnAviXHhGS6N1PjN0wcQQsQ1+FBZxsj0SzpmrW2Y=";
    };
    date = "2024-10-27";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "3e450cd85243da99dc23ebbf14f9c70e9a0c26a4";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "3e450cd85243da99dc23ebbf14f9c70e9a0c26a4";
      fetchSubmodules = false;
      sha256 = "sha256-VTyj1xnw4aL2609HTpJLdNRNnk5607YSk/qacQG8xL4=";
    };
    date = "2024-10-25";
  };
  nvim-ts-autotag = {
    pname = "nvim-ts-autotag";
    version = "e239a560f338be31337e7abc3ee42515daf23f5e";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "e239a560f338be31337e7abc3ee42515daf23f5e";
      fetchSubmodules = false;
      sha256 = "sha256-QEzUKvT+ChYSa9F4zg3Lw+7Sj0JzJem9nh2mWmS8Y+I=";
    };
    date = "2024-08-27";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "19d257cf889f79f4022163c3fbb5e08639077bd8";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "19d257cf889f79f4022163c3fbb5e08639077bd8";
      fetchSubmodules = false;
      sha256 = "sha256-SUWEOp+QcfHjYaqqr4Zwvh0x91IAJXvrdMkQtuWMlGc=";
    };
    date = "2024-10-11";
  };
  octo-nvim = {
    pname = "octo-nvim";
    version = "84a4f195bca82b99d0bf1c8acf64fda00eb0a118";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "84a4f195bca82b99d0bf1c8acf64fda00eb0a118";
      fetchSubmodules = false;
      sha256 = "sha256-tWKct1i4yQ+6PCLvaJgUGq0O0ToIeFKbdMWrDnSgyiU=";
    };
    date = "2024-10-26";
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "2d9b06177a975543726ce5c73fca176cedbffe9d";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "2d9b06177a975543726ce5c73fca176cedbffe9d";
      fetchSubmodules = false;
      sha256 = "sha256-bmmPekAvuBvLQmrnnX0n+FRBqfVxBsObhxIEkDGAla4=";
    };
    date = "2024-09-17";
  };
  presence-nvim = {
    pname = "presence-nvim";
    version = "87c857a56b7703f976d3a5ef15967d80508df6e6";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "87c857a56b7703f976d3a5ef15967d80508df6e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZpsunLsn//zYgUtmAm5FqKVueVd/Pa1r55ZDqxCimBk=";
    };
    date = "2023-01-29";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "d227e6c9879bb50af35cd733461198666981d482";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "d227e6c9879bb50af35cd733461198666981d482";
      fetchSubmodules = false;
      sha256 = "sha256-3Wovs/DREnbch7BtkmQeTXsb91AbZdb+N8TAVikbd88=";
    };
    date = "2024-09-26";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "f0e11ea356e269e2719811f5388a04ff7b215f7f";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "f0e11ea356e269e2719811f5388a04ff7b215f7f";
      fetchSubmodules = false;
      sha256 = "sha256-gyWNOVcC+qG/3gNPlI3/fBuwi+NUIec3vz29e3ZwPtY=";
    };
    date = "2024-10-27";
  };
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "e8835ae8e941e940ed3418c3a77976a2bacc52e4";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "e8835ae8e941e940ed3418c3a77976a2bacc52e4";
      fetchSubmodules = false;
      sha256 = "sha256-dtW5d0CWnLfgg63k99oV0wW6Xb8taope3jzd6zvpb/4=";
    };
    date = "2024-10-27";
  };
  tagalong-vim = {
    pname = "tagalong-vim";
    version = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
    src = fetchFromGitHub {
      owner = "AndrewRadev";
      repo = "tagalong.vim";
      rev = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
      fetchSubmodules = false;
      sha256 = "sha256-zTdq7hg+tPTy803o+f3gIzb7TCw4KRgKAaLf7bBC1A4=";
    };
    date = "2023-09-07";
  };
  telescope-file-browser-nvim = {
    pname = "telescope-file-browser-nvim";
    version = "626998e5c1b71c130d8bc6cf7abb6709b98287bb";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "626998e5c1b71c130d8bc6cf7abb6709b98287bb";
      fetchSubmodules = false;
      sha256 = "sha256-VJbRi91TTOwUkQYyTM6Njl7MtX8/mOjINiqWYWEtyxg=";
    };
    date = "2024-10-24";
  };
  telescope-nvim = {
    pname = "telescope-nvim";
    version = "37dc9233a473dd6c3f54456ef9994d8f77c80211";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "37dc9233a473dd6c3f54456ef9994d8f77c80211";
      fetchSubmodules = false;
      sha256 = "sha256-zidYSt0WrnATuCpSGGhYuafNpPPN6dJ6hEuCgFytfEk=";
    };
    date = "2024-10-26";
  };
  telescope-project-nvim = {
    pname = "telescope-project-nvim";
    version = "796200876bb0fe8157b8eb1ce03d927d3827a052";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "796200876bb0fe8157b8eb1ce03d927d3827a052";
      fetchSubmodules = false;
      sha256 = "sha256-wO/cm5PT1L0hFr/CX466w0UimoFg/tWrDK8T0QeKZMU=";
    };
    date = "2024-09-09";
  };
  todo-comments-nvim = {
    pname = "todo-comments-nvim";
    version = "ae0a2afb47cf7395dc400e5dc4e05274bf4fb9e0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "ae0a2afb47cf7395dc400e5dc4e05274bf4fb9e0";
      fetchSubmodules = false;
      sha256 = "sha256-EH4Sy7qNkzOgA1INFzrtsRfD79TgMqSbKUdundyw22w=";
    };
    date = "2024-09-16";
  };
  toggleterm-nvim = {
    pname = "toggleterm-nvim";
    version = "137d06fb103952a0fb567882bb8527e2f92d327d";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "137d06fb103952a0fb567882bb8527e2f92d327d";
      fetchSubmodules = false;
      sha256 = "sha256-VlHE5nFHDO6GRRM44TqtcWSk2k0NfeCndp7of/35ta4=";
    };
    date = "2024-08-08";
  };
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "2f3b537f2207ce32f4459f9d56746ee013b5e01b";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "2f3b537f2207ce32f4459f9d56746ee013b5e01b";
      fetchSubmodules = false;
      sha256 = "sha256-J0Gor5thMqe6T/4PYC8I1RAywfec0eWU1O+GoHUiHnI=";
    };
    date = "2024-10-23";
  };
  twilight-nvim = {
    pname = "twilight-nvim";
    version = "1584c0b0a979b71fd86b18d302ba84e9aba85b1b";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "twilight.nvim";
      rev = "1584c0b0a979b71fd86b18d302ba84e9aba85b1b";
      fetchSubmodules = false;
      sha256 = "sha256-sC9DSgkQw+jHvi+xUP+iWSSLV0kIWWmrom2Mq5q+RJo=";
    };
    date = "2024-07-22";
  };
  typescript-tools-nvim = {
    pname = "typescript-tools-nvim";
    version = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
      fetchSubmodules = false;
      sha256 = "sha256-8WH/eCff1liDVaezZFvu6RqCtXU4Uwq80BlWiH+tQME=";
    };
    date = "2024-07-18";
  };
  venv-selector-nvim = {
    pname = "venv-selector-nvim";
    version = "e82594274bf7b54387f9a2abe65f74909ac66e97";
    src = fetchFromGitHub {
      owner = "linux-cultist";
      repo = "venv-selector.nvim";
      rev = "e82594274bf7b54387f9a2abe65f74909ac66e97";
      fetchSubmodules = false;
      sha256 = "sha256-AyxITaKoeM+l+RbFp2UWy0zVrxrIxy8S/oDJsEr/VDQ=";
    };
    date = "2024-09-15";
  };
  vim-applescript = {
    pname = "vim-applescript";
    version = "a39af8fc7e4caf581366e2917d558f6232e4db36";
    src = fetchFromGitHub {
      owner = "mityu";
      repo = "vim-applescript";
      rev = "a39af8fc7e4caf581366e2917d558f6232e4db36";
      fetchSubmodules = false;
      sha256 = "sha256-9asF5VMaKz3lfSsCTrvkicffgMbHY88wDZ+LJR9QTvY=";
    };
    date = "2022-01-21";
  };
  vim-dadbod = {
    pname = "vim-dadbod";
    version = "fe5a55e92b2dded7c404006147ef97fb073d8b1b";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-dadbod";
      rev = "fe5a55e92b2dded7c404006147ef97fb073d8b1b";
      fetchSubmodules = false;
      sha256 = "sha256-wRkd6DRpjDvazJrjbIAndNrnjMIrKOGKQvNfnk+9yeM=";
    };
    date = "2024-10-18";
  };
  vim-dadbod-completion = {
    pname = "vim-dadbod-completion";
    version = "880f7e9f2959e567c718d52550f9fae1aa07aa81";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-completion";
      rev = "880f7e9f2959e567c718d52550f9fae1aa07aa81";
      fetchSubmodules = false;
      sha256 = "sha256-kci8ksgSRPmRhwTYw7Ya1v4hwPjN4BLFjV6+6YiK1hA=";
    };
    date = "2024-08-15";
  };
  vim-dadbod-ui = {
    pname = "vim-dadbod-ui";
    version = "f29c85ab42861c6ef683289b0c6a51e0d436dcf6";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-ui";
      rev = "f29c85ab42861c6ef683289b0c6a51e0d436dcf6";
      fetchSubmodules = false;
      sha256 = "sha256-mgY/vVrv8hq7TtwX4tvHXfGX3Z3PIcRGdt299WU4YhI=";
    };
    date = "2024-09-23";
  };
  vim-gnupg = {
    pname = "vim-gnupg";
    version = "f9b608f29003dfde6450931dc0f495a912973a88";
    src = fetchFromGitHub {
      owner = "jamessan";
      repo = "vim-gnupg";
      rev = "f9b608f29003dfde6450931dc0f495a912973a88";
      fetchSubmodules = false;
      sha256 = "sha256-B6hSEeNjJdDUDjM0DlmAxc3zRRcJz91//GPk6rCWn6I=";
    };
    date = "2022-05-18";
  };
  vim-helm = {
    pname = "vim-helm";
    version = "ae1ebc160d2b9b90108477ab10df7a4fc501e358";
    src = fetchFromGitHub {
      owner = "towolf";
      repo = "vim-helm";
      rev = "ae1ebc160d2b9b90108477ab10df7a4fc501e358";
      fetchSubmodules = false;
      sha256 = "sha256-xrZ8MCuewAN/qIqSrbTuCtZocYZvXSSet26MYrYumxI=";
    };
    date = "2024-05-31";
  };
  vim-table-mode = {
    pname = "vim-table-mode";
    version = "e4365bde024f73e205eefa2fb78e3029ddb92ea9";
    src = fetchFromGitHub {
      owner = "dhruvasagar";
      repo = "vim-table-mode";
      rev = "e4365bde024f73e205eefa2fb78e3029ddb92ea9";
      fetchSubmodules = false;
      sha256 = "sha256-8p40cId8dQVhXHuusk2Mn2esRZm8vcY5EZbAXBPU/Fg=";
    };
    date = "2024-03-14";
  };
  vim-tera = {
    pname = "vim-tera";
    version = "235fb7e7e76dfffc0596fabc1e090880bce48844";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "vim-tera";
      rev = "235fb7e7e76dfffc0596fabc1e090880bce48844";
      fetchSubmodules = false;
      sha256 = "sha256-Zs3rRAwTp9iZc5oOkiR88j7LX7YmDrEELXt29h+j55w=";
    };
    date = "2024-05-29";
  };
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "8badb359f7ab8711e2575ef75dfe6fbbd87e4821";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "8badb359f7ab8711e2575ef75dfe6fbbd87e4821";
      fetchSubmodules = false;
      sha256 = "sha256-crECQnWpptz1A/hOndHPEduK6MqWQH8kyf58h+4snHo=";
    };
    date = "2024-10-02";
  };
  winshift-nvim = {
    pname = "winshift-nvim";
    version = "37468ed6f385dfb50402368669766504c0e15583";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "winshift.nvim";
      rev = "37468ed6f385dfb50402368669766504c0e15583";
      fetchSubmodules = false;
      sha256 = "sha256-mW3kaducHWRlDx18WcwcbWDlNnAyHgELS3XjpeFFCgs=";
    };
    date = "2022-09-06";
  };
  zen-mode-nvim = {
    pname = "zen-mode-nvim";
    version = "29b292bdc58b76a6c8f294c961a8bf92c5a6ebd6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "29b292bdc58b76a6c8f294c961a8bf92c5a6ebd6";
      fetchSubmodules = false;
      sha256 = "sha256-iHGsnFG1PBup3/+JbSwXf/TerQ7PNXkp9gKVznmRbTE=";
    };
    date = "2024-07-22";
  };
}
