# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  auto-dark-mode-nvim = {
    pname = "auto-dark-mode-nvim";
    version = "02ef9553e2a1d6e861bc6955d58ce5883d28a6ad";
    src = fetchFromGitHub {
      owner = "f-person";
      repo = "auto-dark-mode.nvim";
      rev = "02ef9553e2a1d6e861bc6955d58ce5883d28a6ad";
      fetchSubmodules = false;
      sha256 = "sha256-FTXakglUrqifEXjzES6M4L+rthItu5rlw6QyIOLYNOc=";
    };
    date = "2025-01-25";
  };
  milspec-nvim = {
    pname = "milspec-nvim";
    version = "11d492e7c3ef3b16a446415b303d239a26643f2b";
    src = fetchFromGitHub {
      owner = "nekowinston";
      repo = "milspec.nvim";
      rev = "11d492e7c3ef3b16a446415b303d239a26643f2b";
      fetchSubmodules = false;
      sha256 = "sha256-xk8gvWAuaBKjv2ZYMuE3NCozq6ahP7KA/BIoMd8tjmA=";
    };
    date = "2024-12-21";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "270e235b014f0c37bf362eb1e8913d66bba33a2e";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "270e235b014f0c37bf362eb1e8913d66bba33a2e";
      fetchSubmodules = false;
      sha256 = "sha256-0CB7/hqj3zEZPQUOQoaETcNzFJcQyKt3k7hIXoArhZg=";
    };
    date = "2025-01-19";
  };
  venv-selector-nvim = {
    pname = "venv-selector-nvim";
    version = "e82594274bf7b54387f9a2abe65f74909ac66e97";
    src = fetchFromGitHub {
      owner = "linux-cultist";
      repo = "venv-selector.nvim";
      rev = "e82594274bf7b54387f9a2abe65f74909ac66e97";
      fetchSubmodules = false;
      sha256 = "sha256-AyxITaKoeM+l+RbFp2UWy0zVrxrIxy8S/oDJsEr/VDQ=";
    };
    date = "2024-09-15";
  };
  vim-applescript = {
    pname = "vim-applescript";
    version = "a39af8fc7e4caf581366e2917d558f6232e4db36";
    src = fetchFromGitHub {
      owner = "mityu";
      repo = "vim-applescript";
      rev = "a39af8fc7e4caf581366e2917d558f6232e4db36";
      fetchSubmodules = false;
      sha256 = "sha256-9asF5VMaKz3lfSsCTrvkicffgMbHY88wDZ+LJR9QTvY=";
    };
    date = "2022-01-21";
  };
  vim-tera = {
    pname = "vim-tera";
    version = "235fb7e7e76dfffc0596fabc1e090880bce48844";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "vim-tera";
      rev = "235fb7e7e76dfffc0596fabc1e090880bce48844";
      fetchSubmodules = false;
      sha256 = "sha256-Zs3rRAwTp9iZc5oOkiR88j7LX7YmDrEELXt29h+j55w=";
    };
    date = "2024-05-29";
  };
}
