return function()
	local dap = require("dap")
	local dapui = require("dapui")
	local dapui_widgets = require("dap.ui.widgets")

	dap.listeners.before.attach.dapui_config = function()
		dapui.open()
	end
	dap.listeners.before.launch.dapui_config = function()
		dapui.open()
	end
	dap.listeners.before.event_terminated.dapui_config = function()
		dapui.close()
	end
	dap.listeners.before.event_exited.dapui_config = function()
		dapui.close()
	end

	vim.api.nvim_create_user_command("DapToggleUI", function()
		dapui.toggle()
	end, { desc = "Toggle DAP UI" })

	vim.keymap.set("n", "<F5>", function()
		dap.continue()
	end)
	vim.keymap.set("n", "<F10>", function()
		dap.step_over()
	end)
	vim.keymap.set("n", "<F11>", function()
		dap.step_into()
	end)
	vim.keymap.set("n", "<F12>", function()
		dap.step_out()
	end)
	vim.keymap.set("n", "<leader>b", function()
		dap.toggle_breakpoint()
	end)
	vim.keymap.set("n", "<leader>B", function()
		dap.set_breakpoint()
	end)
	vim.keymap.set("n", "<leader>lp", function()
		dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
	end)
	vim.keymap.set("n", "<leader>dr", function()
		dap.repl.open()
	end)
	vim.keymap.set("n", "<leader>dl", function()
		dap.run_last()
	end)
	vim.keymap.set({ "n", "v" }, "<leader>dh", function()
		dapui_widgets.hover()
	end)
	vim.keymap.set({ "n", "v" }, "<leader>dp", function()
		dapui_widgets.preview()
	end)
	vim.keymap.set("n", "<leader>df", function()
		dapui_widgets.centered_float(dapui_widgets.frames)
	end)
	vim.keymap.set("n", "<leader>ds", function()
		dapui_widgets.centered_float(dapui_widgets.scopes)
	end)
end
